=== UCSD-HCI/PenProtocol/SpacesPen/iserver/iserver.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--iServer XML import/export format-->
<!ELEMENT iserver (link* | individual* | group* | layer* | document* | page* | rectangle* | polygon* | circle* | ellipse* | complexShape* | textComp* | medium* | omswe* | activeComponent* | rfidSpace* | rfidTag* | parameter* | xhtmlDocument* | xhtmlSelector* | template* | flashMovie* | flashPropertySelector* | flashMethodSelector*)+>

<!ELEMENT link ((name, creator?, authorised?, unauthorised?, properties?), (sources?, targets?))>
<!ATTLIST link
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	templates IDREFS #IMPLIED
	sources IDREFS #IMPLIED
	targets IDREFS #IMPLIED
>
<!ELEMENT individual ((name, description, preferences?, members?), (login, password))>
<!ATTLIST individual
	id ID #IMPLIED
	preferences IDREFS #IMPLIED
>
<!ELEMENT group (name, description, preferences?, members?)>
<!ATTLIST group
	id ID #IMPLIED
	preferences IDREFS #IMPLIED
	members IDREFS #IMPLIED
>
<!ELEMENT layer (name)>
<!ATTLIST layer
	id ID #IMPLIED
>
<!ELEMENT document ((name, creator?, authorised?, unauthorised?, properties?), (template*), (id, size?, content, pages?))>
<!ATTLIST document
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	templates IDREFS #IMPLIED
	size IDREF #IMPLIED
	pages IDREFS #IMPLIED
>
<!ELEMENT page ((name, creator?, authorised?, unauthorised?, properties?), (template*), (size?, number, document?))>
<!ATTLIST page
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	templates IDREFS #IMPLIED
	document IDREF #REQUIRED
	size IDREF #IMPLIED
>
<!ELEMENT rectangle ((name, creator?, authorised?, unauthorised?, properties?), (layer?)?, (upperLeft, size))>
<!ATTLIST rectangle
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	layer IDREF #IMPLIED
	resource IDREF #REQUIRED
>
<!ELEMENT polygon ((name, creator?, authorised?, unauthorised?, properties?), (layer?)?, (point+))>
<!ATTLIST polygon
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	layer IDREF #IMPLIED
	resource IDREF #REQUIRED
>
<!ELEMENT circle ((name, creator?, authorised?, unauthorised?, properties?), (layer?)?, (centre, radius))>
<!ATTLIST circle
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	layer IDREF #IMPLIED
	resource IDREF #REQUIRED
>
<!ELEMENT ellipse ((name, creator?, authorised?, unauthorised?, properties?), (layer?)?, (centre, width, height))>
<!ATTLIST ellipse
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	layer IDREF #IMPLIED
	resource IDREF #REQUIRED
>
<!ELEMENT complexShape ((name, creator?, authorised?, unauthorised?, properties?), (layer?)?, (shapes*))>
<!ATTLIST complexShape
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	layer IDREF #IMPLIED
	resource IDREF #REQUIRED
	shapes IDREFS #IMPLIED
>
<!ELEMENT textComp ((name, creator?, authorised?, unauthorised?, properties?), (template*), (content))>
<!ATTLIST textComp
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	templates IDREFS #IMPLIED
>
<!ELEMENT medium ((name, creator?, authorised?, unauthorised?, properties?), (template*), (description, content, collection?))>
<!ATTLIST medium
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	templates IDREFS #IMPLIED
>
<!ELEMENT omswe ((name, creator?, authorised?, unauthorised?, properties?), (template*), (description, content, collection?))>
<!ATTLIST omswe
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	templates IDREFS #IMPLIED
>
<!ELEMENT activeComponent ((name, creator?, authorised?, unauthorised?, properties?), (template*), (identifier, timeout?))>
<!ATTLIST activeComponent
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	templates IDREFS #IMPLIED
>
<!ELEMENT rfidSpace ((name, creator?, authorised?, unauthorised?, properties?), (template*))>
<!ATTLIST rfidSpace
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	templates IDREFS #IMPLIED
>
<!ELEMENT rfidTag ((name, creator?, authorised?, unauthorised?, properties?), (layer?)?, (id))>
<!ATTLIST rfidTag
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	layer IDREF #IMPLIED
	resource IDREF #REQUIRED
>

<!ELEMENT flashMovie ((name, creator?, authorised?, unauthorised?, properties?), (template*), (content))>
<!ATTLIST flashMovie
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	templates IDREFS #IMPLIED
>

<!ELEMENT flashPropertySelector ((name, creator?, authorised?, unauthorised?, properties?), (layer?)?, (object), (propertyName, value, endValue))>
<!ATTLIST flashPropertySelector
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	layer IDREF #IMPLIED
	resource IDREF #REQUIRED
>

<!ELEMENT object (#PCDATA)>
<!ELEMENT propertyName (#PCDATA)>
<!ELEMENT endValue (#PCDATA)>

<!ELEMENT flashMethodSelector ((name, creator?, authorised?, unauthorised?, properties?), (layer?)?, (object), (methodName, arguments))>
<!ATTLIST flashMethodSelector
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	layer IDREF #IMPLIED
	resource IDREF #REQUIRED
>

<!ELEMENT methodName (#PCDATA)>

<!ELEMENT arguments (argument+)>
<!ELEMENT argument (key, value)>

<!ELEMENT selector (#PCDATA)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT creator (individual)>
<!ATTLIST creator
	individual IDREF #IMPLIED
>

<!ELEMENT identifier (#PCDATA)>
<!ELEMENT uri (#PCDATA)>
<!ELEMENT timeout (#PCDATA)>
<!ELEMENT data (#PCDATA)>

<!ELEMENT authorised (individual* | group*)+>
<!ATTLIST authorised
	users IDREFS #IMPLIED
>
<!ELEMENT unauthorised (individual* | group*)*>
<!ATTLIST unauthorised
	users IDREFS #IMPLIED
>
<!ELEMENT properties (parameter+)>
<!ELEMENT sources (rectangle*)>
<!ELEMENT targets (rectangle*)+>
<!ELEMENT description (#PCDATA)>
<!ELEMENT preferences (parameter+)>
<!ELEMENT members (individual*, group*)>
<!ELEMENT login (#PCDATA)>
<!ELEMENT password (#PCDATA)>

<!ELEMENT id (#PCDATA)>
<!ELEMENT size (width, height)>
<!ATTLIST size
	id ID #IMPLIED
>
<!ELEMENT content (#PCDATA)>
<!ELEMENT pages (page+)>

<!ELEMENT number (#PCDATA)>

<!ELEMENT upperLeft (point)>

<!ELEMENT point (x, y)>

<!ELEMENT centre (point)>
<!ELEMENT radius (#PCDATA)>

<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>

<!ELEMENT shapes (rectangle* | polygon* | circle* | ellipse* | complexShape*)>

<!ELEMENT collection (#PCDATA)>

<!ELEMENT parameter (key, value)>
<!ATTLIST parameter
	id ID #IMPLIED
>

<!ELEMENT template ((name, creator?, authorised?, unauthorised?, properties?), (template*))>
<!ATTLIST template
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
>

<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>

<!ELEMENT key (#PCDATA)>
<!ELEMENT value (#PCDATA)>

<!ELEMENT xhtmlDocument ((name, creator?, authorised?, unauthorised?, properties?), (uri))>
<!ATTLIST xhtmlDocument
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
>

<!ELEMENT xhtmlSelector ((name, creator?, authorised?, unauthorised?, properties?), (layer?)?, (xpointer))>
<!ATTLIST xhtmlSelector
	id ID #IMPLIED
	creator IDREF #IMPLIED
	properties IDREFS #IMPLIED
	authorised IDREFS #IMPLIED
	unauthorised IDREFS #IMPLIED
	layer IDREF #IMPLIED
	resource IDREF #REQUIRED
>

<!ELEMENT xpointer (#PCDATA)>

=== UCSD-HCI/PenProtocol/SpacesPen/iserver/spaces.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE iserver SYSTEM "./iserver.dtd">
<iserver>
	<layer id="defaultLayer">
		<name>Default Layer</name>
	</layer>
	<individual id="nadir">
		<name>Nadir Weibel</name>
		<description>Postdoctoral Researcher, UCSD</description>
		<login>weibel</login>
		<password>weibel</password>
	</individual>
	<document id="spaces_document" creator="nadir"
		templates="spaces_template">
		<name>Spaces Remote Control</name>
		<id>spaces_document</id>
		<size>
			<width>216</width>
			<height>279</height>
		</size>
		<content>none</content>
	</document>
	<template id="spaces_template" creator="nadir">
		<name>spaces_template</name>
	</template>
	<page id="spaces_page_1" creator="nadir" document="spaces_document">
		<name>Spaces Page 1</name>
		<number>1</number>
	</page>

	<rectangle resource="spaces_template" creator="nadir"
		id="page_shape" layer="defaultLayer">
		<name>Power</name>
		<upperLeft>
			<point>
				<x>0</x>
				<y>0</y>
			</point>
		</upperLeft>
		<size>
			<width>216</width>
			<height>279</height>
		</size>
	</rectangle>
	
	<activeComponent id="page_ac" creator="nadir">
		<name>Page AC</name>
		<properties>
			<parameter>
				<key>org.ximtec.iserver.ac:buttonNr</key>
				<value>1</value>
			</parameter>
		</properties>
		<identifier>edu.ucsd.hci.spaces.BUTTON</identifier>
	</activeComponent>
	
	<link id="page_link" creator="nadir" sources="page_shape"
		targets="page_ac">
		<name>Link for Page AC</name>
	</link>

<!-- 
	<rectangle resource="spaces_template" creator="nadir"
		id="power_button" layer="defaultLayer">
		<name>Power</name>
		<upperLeft>
			<point>
				<x>163</x>
				<y>17</y>
			</point>
		</upperLeft>
		<size>
			<width>23</width>
			<height>15</height>
		</size>
	</rectangle>
	

	<activeComponent id="button_1_ac" creator="nadir">
		<name>spaces Power AC</name>
		<properties>
			<parameter>
				<key>org.ximtec.iserver.ac:buttonNr</key>
				<value>1</value>
			</parameter>
		</properties>
		<identifier>edu.ucsd.hci.spaces.BUTTON</identifier>
	</activeComponent>
	

	<link id="button_1_link" creator="nadir" sources="button_1"
		targets="button_1_ac">
		<name>Link for spaces Power</name>
	</link>
	
	

	<rectangle resource="spaces_template" creator="nadir"
		id="button_2" layer="defaultLayer">
		<name>Button A</name>
		<upperLeft>
			<point>
				<x>28</x>
				<y>47</y>
			</point>
		</upperLeft>
		<size>
			<width>38</width>
			<height>36</height>
		</size>
	</rectangle>
	

	<activeComponent id="button_2_ac" creator="nadir">
		<name>spaces Button A AC</name>
		<properties>
			<parameter>
				<key>org.ximtec.iserver.ac:buttonNr</key>
				<value>2</value>
			</parameter>
		</properties>
		<identifier>edu.ucsd.hci.spaces.BUTTON</identifier>
	</activeComponent>
	

	<link id="button_2_link" creator="nadir" sources="button_2"
		targets="button_2_ac">
		<name>Link for spaces Button A</name>
	</link>
	
	

	<rectangle resource="spaces_template" creator="nadir"
		id="button_3" layer="defaultLayer">
		<name>Button B</name>
		<upperLeft>
			<point>
				<x>86</x>
				<y>47</y>
			</point>
		</upperLeft>
		<size>
			<width>38</width>
			<height>36</height>
		</size>
	</rectangle>
	

	<activeComponent id="button_3_ac" creator="nadir">
		<name>spaces Button B AC</name>
		<properties>
			<parameter>
				<key>org.ximtec.iserver.ac:buttonNr</key>
				<value>3</value>
			</parameter>
		</properties>
		<identifier>edu.ucsd.hci.spaces.BUTTON</identifier>
	</activeComponent>
	

	<link id="button_3_link" creator="nadir" sources="button_3"
		targets="button_3_ac">
		<name>Link for spaces Button B</name>
	</link>
	
	

	<rectangle resource="spaces_template" creator="nadir"
		id="button_4" layer="defaultLayer">
		<name>Button C</name>
		<upperLeft>
			<point>
				<x>145</x>
				<y>47</y>
			</point>
		</upperLeft>
		<size>
			<width>38</width>
			<height>36</height>
		</size>
	</rectangle>
	

	<activeComponent id="button_4_ac" creator="nadir">
		<name>spaces Button C AC</name>
		<properties>
			<parameter>
				<key>org.ximtec.iserver.ac:buttonNr</key>
				<value>4</value>
			</parameter>
		</properties>
		<identifier>edu.ucsd.hci.spaces.BUTTON</identifier>
	</activeComponent>
	

	<link id="button_4_link" creator="nadir" sources="button_4"
		targets="button_4_ac">
		<name>Link for spaces Button C</name>
	</link>
	
	

	<rectangle resource="spaces_template" creator="nadir"
		id="button_5" layer="defaultLayer">
		<name>ENTER</name>
		<upperLeft>
			<point>
				<x>69</x>
				<y>99</y>
			</point>
		</upperLeft>
		<size>
			<width>76</width>
			<height>14</height>
		</size>
	</rectangle>
	

	<activeComponent id="button_5_ac" creator="nadir">
		<name>spaces ENTER AC</name>
		<properties>
			<parameter>
				<key>org.ximtec.iserver.ac:buttonNr</key>
				<value>5</value>
			</parameter>
		</properties>
		<identifier>edu.ucsd.hci.spaces.BUTTON</identifier>
	</activeComponent>
	

	<link id="button_5_link" creator="nadir" sources="button_5"
		targets="button_5_ac">
		<name>Link for spaces ENTER</name>
	</link>
	
	

	<rectangle resource="spaces_template" creator="nadir"
		id="button_6" layer="defaultLayer">
		<name>Last</name>
		<upperLeft>
			<point>
				<x>28</x>
				<y>99</y>
			</point>
		</upperLeft>
		<size>
			<width>29</width>
			<height>15</height>
		</size>
	</rectangle>
	

	<activeComponent id="button_6_ac" creator="nadir">
		<name>spaces Last AC</name>
		<properties>
			<parameter>
				<key>org.ximtec.iserver.ac:buttonNr</key>
				<value>6</value>
			</parameter>
		</properties>
		<identifier>edu.ucsd.hci.spaces.BUTTON</identifier>
	</activeComponent>
	

	<link id="button_6_link" creator="nadir" sources="button_6"
		targets="button_6_ac">
		<name>Link for spaces Last</name>
	</link>
	
	

	<rectangle resource="spaces_template" creator="nadir"
		id="button_7" layer="defaultLayer">
		<name>Next</name>
		<upperLeft>
			<point>
				<x>157</x>
				<y>99</y>
			</point>
		</upperLeft>
		<size>
			<width>29</width>
			<height>15</height>
		</size>
	</rectangle>
	

	<activeComponent id="button_7_ac" creator="nadir">
		<name>spaces Next AC</name>
		<properties>
			<parameter>
				<key>org.ximtec.iserver.ac:buttonNr</key>
				<value>7</value>
			</parameter>
		</properties>
		<identifier>edu.ucsd.hci.spaces.BUTTON</identifier>
	</activeComponent>
	

	<link id="button_7_link" creator="nadir" sources="button_7"
		targets="button_7_ac">
		<name>Link for spaces Next</name>
	</link>
	
	

	<rectangle resource="spaces_template" creator="nadir"
		id="button_8" layer="defaultLayer">
		<name>NUM 1</name>
		<upperLeft>
			<point>
				<x>69</x>
				<y>121</y>
			</point>
		</upperLeft>
		<size>
			<width>25</width>
			<height>26</height>
		</size>
	</rectangle>
	

	<activeComponent id="button_8_ac" creator="nadir">
		<name>spaces NUM 1 AC</name>
		<properties>
			<parameter>
				<key>org.ximtec.iserver.ac:buttonNr</key>
				<value>8</value>
			</parameter>
		</properties>
		<identifier>edu.ucsd.hci.spaces.BUTTON</identifier>
	</activeComponent>
	

	<link id="button_8_link" creator="nadir" sources="button_8"
		targets="button_8_ac">
		<name>Link for spaces NUM 1</name>
	</link>
	
	

	<rectangle resource="spaces_template" creator="nadir"
		id="button_9" layer="defaultLayer">
		<name>NUM 2</name>
		<upperLeft>
			<point>
				<x>94</x>
				<y>121</y>
			</point>
		</upperLeft>
		<size>
			<width>25</width>
			<height>26</height>
		</size>
	</rectangle>
	

	<activeComponent id="button_9_ac" creator="nadir">
		<name>spaces NUM 2 AC</name>
		<properties>
			<parameter>
				<key>org.ximtec.iserver.ac:buttonNr</key>
				<value>9</value>
			</parameter>
		</properties>
		<identifier>edu.ucsd.hci.spaces.BUTTON</identifier>
	</activeComponent>
	

	<link id="button_9_link" creator="nadir" sources="button_9"
		targets="button_9_ac">
		<name>Link for spaces NUM 2</name>
	</link>
	
	

	<rectangle resource="spaces_template" creator="nadir"
		id="button_10" layer="defaultLayer">
		<name>NUM 3</name>
		<upperLeft>
			<point>
				<x>119</x>
				<y>121</y>
			</point>
		</upperLeft>
		<size>
			<width>25</width>
			<height>26</height>
		</size>
	</rectangle>
	

	<activeComponent id="button_10_ac" creator="nadir">
		<name>spaces NUM 3 AC</name>
		<properties>
			<parameter>
				<key>org.ximtec.iserver.ac:buttonNr</key>
				<value>10</value>
			</parameter>
		</properties>
		<identifier>edu.ucsd.hci.spaces.BUTTON</identifier>
	</activeComponent>
	

	<link id="button_10_link" creator="nadir" sources="button_10"
		targets="button_10_ac">
		<name>Link for spaces NUM 3</name>
	</link>
	
	

	<rectangle resource="spaces_template" creator="nadir"
		id="button_11" layer="defaultLayer">
		<name>NUM 4</name>
		<upperLeft>
			<point>
				<x>69</x>
				<y>146</y>
			</point>
		</upperLeft>
		<size>
			<width>25</width>
			<height>26</height>
		</size>
	</rectangle>
	

	<activeComponent id="button_11_ac" creator="nadir">
		<name>spaces NUM 4 AC</name>
		<properties>
			<parameter>
				<key>org.ximtec.iserver.ac:buttonNr</key>
				<value>11</value>
			</parameter>
		</properties>
		<identifier>edu.ucsd.hci.spaces.BUTTON</identifier>
	</activeComponent>
	

	<link id="button_11_link" creator="nadir" sources="button_11"
		targets="button_11_ac">
		<name>Link for spaces NUM 4</name>
	</link>
	
	

	<rectangle resource="spaces_template" creator="nadir"
		id="button_12" layer="defaultLayer">
		<name>NUM 5</name>
		<upperLeft>
			<point>
				<x>94</x>
				<y>146</y>
			</point>
		</upperLeft>
		<size>
			<width>25</width>
			<height>26</height>
		</size>
	</rectangle>
